### ISSUE TITLE
Unable to log in to Owncloud using Sailfish client 

### ISSUE THREAD

**Issue by ninepine** [beidl/harbour-owncloud#2]
Hi I'm running Owncloud on my webserver but only have httpnot https.
I've entered my owncloud URL in settings Kbeginning http://) but each time :80 is added by the programme to the domain in the URL. I also don't appear to be able to log in as the screen only shows  a single forward slash in the top right hand corner even after entering the full settings. 
Am I missing something?

**Comment by paolomonella** [comment]
Hi, sorry to re-open an old thread. I have exactly the same issue. I'm using version 0.4 and I keep my owncloud server on a linux machine. I also use http and not htts.

I checked whether the 80 standard port is enabled and it is.

I can access my owncloud on my Jolla through the browser/web interface, the browser/webdav and the SyncEvolution app (caldav and carddav). If useful I can email you my URL. Thank you very much in advance.

**Comment by trondth** [comment]
Did you remember the trailing slash in the url?

**Comment by paolomonella** [comment]
Yes, the trailing slash is there. The "Host address" is in the format
http://servername.dyndns.org/

Then, the app automatically adds the port number (I'm using http, not https), so the result is:
http://servername.dyndns.org:80/
Beidl pointed out that the port number appending is made on purpose.

**Comment by paolomonella** [comment]
OK, my problem is now solved. I was my mistake: I initially erroneously wrote
http://myowncloud.dyndns.org/

When I wrote
http://myowncloud.dyndns.org/owncloud/
everything worked out like a charm.

Please note that in the Jolla app store one of the images in the app's profile, representing a sample configuration screenshot, has the following line:
https://myowncloud.com:443
(without '/owncloud/' at the end). Probably the original configuration in the device from which the screenshot was taken continued with
https://myowncloud.com:443/owncloud/
but the rest of the string was cut off the screenshot because it did not fit the screen.

May I suggest that you change that screenshot, as to avoid other people to get confused in the configuration?
